default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: jenya


test:
  <<: *default
  database: blog_test

development:
  <<: *default
  database: blog_development

production:
  <<: *default
  database: blog_production
